// <auto-generated />
using Ogrenci_ve_Not_Sistemi_AspNetCoreMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ogrenci_ve_Not_Sistemi_AspNetCoreMVC.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ogrenci_ve_Not_Sistemi_AspNetCoreMVC.Models.Dersler", b =>
                {
                    b.Property<int>("DersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DersID"));

                    b.Property<string>("DersAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DersID");

                    b.ToTable("Derslers", "dbo");
                });

            modelBuilder.Entity("Ogrenci_ve_Not_Sistemi_AspNetCoreMVC.Models.Notlar", b =>
                {
                    b.Property<int>("NotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotID"));

                    b.Property<int>("DersID")
                        .HasColumnType("integer");

                    b.Property<int>("Final")
                        .HasColumnType("integer");

                    b.Property<int>("OgrenciID")
                        .HasColumnType("integer");

                    b.Property<int>("Vize")
                        .HasColumnType("integer");

                    b.HasKey("NotID");

                    b.ToTable("Notlars", "dbo");
                });

            modelBuilder.Entity("Ogrenci_ve_Not_Sistemi_AspNetCoreMVC.Models.Ogrenciler", b =>
                {
                    b.Property<int>("OgrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OgrenciID"));

                    b.Property<string>("Cinsiyet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OgrenciAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OgrenciNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OgrenciSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TCK")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OgrenciID");

                    b.ToTable("Ogrencilers", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
